Homework 2
================
Meghan Brown (mmb2355)<br>
2026-10-07

## Problem 0

### libraries

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

## Problem 1

### read and clean data; character to logical variable

``` r
nyc_transit_df =
  read_csv(
    "NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) |> 
  janitor::clean_names() |> 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) |> 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE)
    )
```

In nyc_transit_df, the variables are station name, staion latitude,
station longitude, routes served, entry, exit, vending, entrance type,
and ADA compliance. The data was read and cleaned, and the entry
variable was changed from a character to logical variable. There are
1,868 rows and 20 columns. The data is not tidy yet because “route” and
“route number” are not variables after the prior adjustments.

### Number of distinct stations

``` r
nyc_transit_df |> 
  select(station_name, line) |> 
  distinct()
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # ℹ 455 more rows

There are 465 distinct stations in this datafile.

### ADA compliance

``` r
nyc_transit_df |> 
  filter(ada == TRUE) |> 
  select(station_name, line) |> 
  distinct()
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # ℹ 74 more rows

There are 84 stations that are ADA compliant.

### Proportion of station entrances/exits w/o vending

``` r
nyc_transit_df |> 
  filter(vending == "NO") |> 
  pull(entry) |> 
  mean()
```

    ## [1] 0.3770492

The proportion of station entrances/exits that do not have vending that
allow entrance is 0.38(38%).

### A train

``` r
nyc_transit_df |> 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") |> 
  filter(route == "A") |> 
  select(station_name, line) |> 
  distinct()
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # ℹ 50 more rows

There are 60 stations that serve the A train.

### A train & ADA compliance

``` r
nyc_transit_df |> 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") |> 
  filter(route == "A", ada == TRUE) |> 
  select(station_name, line) |> 
  distinct()
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

There are 17 stations that serve the A line and are ADA compliant.

## Problem 2

### Mr. Trash Wheel

``` r
mr_tw_df =
  readxl::read_excel(
    path = "202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel", 
    na = c("", ".","NA"), 
    skip = 1
    ) |> 
janitor::clean_names() |> 
drop_na(dumpster) |> 
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel",
    year = as.numeric(year),
    plastic_bottles = as.numeric(plastic_bottles)
  )
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
select(mr_tw_df, sports_balls)
```

    ## # A tibble: 740 × 1
    ##    sports_balls
    ##           <int>
    ##  1            7
    ##  2            5
    ##  3            6
    ##  4            6
    ##  5            7
    ##  6            5
    ##  7            3
    ##  8            6
    ##  9            6
    ## 10            7
    ## # ℹ 730 more rows

### Professor Trash Wheel

``` r
prof_tw_df =
  readxl::read_excel(
    path = "202610 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel", 
    na = c("", ".","NA"), 
    skip = 1
    ) |> 
janitor::clean_names() |> 
drop_na(dumpster) |> 
mutate(
  trash_wheel = "Professor Trash Wheel",
  year = as.numeric(year),
  plastic_bottles = as.numeric(plastic_bottles)
)
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `plastic_bottles = as.numeric(plastic_bottles)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

### Gwynnda the Good Wheel of the W

``` r
gwynnda_df =
  readxl::read_excel(
    path = "202610 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynnda the Good Wheel of the W", 
    na = c("", ".","NA"), 
    skip = 1
    ) |> 
janitor::clean_names() |> 
drop_na(dumpster) |> 
mutate(
  trash_wheel = "Gwynnda the Good Wheel of the W",
  year = as.numeric(year),
  plastic_bottles = as.numeric(plastic_bottles)
)
```

### Combine trash wheel dfs

``` r
trash_wheel_df =
  bind_rows(mr_tw_df, prof_tw_df, gwynnda_df) |> 
  relocate(trash_wheel)

nrow(trash_wheel_df)
```

    ## [1] 1269

``` r
prof_tw_df |>
  pull(weight_tons)|>
  sum(na.rm = TRUE)
```

    ## [1] 294.96

``` r
gwynnda_df |> 
  filter(between(date, as.Date("2022-06-01"), as.Date("2022-06-30"))) |>
  summarize(total_cigs = sum(cigarette_butts, na.rm = TRUE))
```

    ## # A tibble: 1 × 1
    ##   total_cigs
    ##        <dbl>
    ## 1      18120

In trash_wheel_df, there are 1,269 observations and key variables are
plastic bottles, dumpster, year, and trash wheel type. The total weight
of trash collected by Professor Trash Wheel is 294.96 tons. There is a
total of 18,120 cigarette butts collected by Gwynnda in June of 2022.

## Problem 3

### Upload MCI baseline data

``` r
baseline_raw_df =
  read.csv("MCI_baseline.csv", 
  na = c("",".","NA"), skip = 1) |>
  janitor::clean_names() |>
  mutate(
    sex = recode_values(
      sex,
      0 ~ "Female",
      1 ~ "Male"),
    apoe4 = recode_values(
      apoe4,
      0 ~ "Non-Carrier",
      1 ~ "Carrier")
  )

baseline_new_df =
  baseline_raw_df |>
    filter(is.na(age_at_onset) | age_at_onset > current_age)
  
nrow(baseline_raw_df)
```

    ## [1] 483

``` r
nrow(baseline_new_df)
```

    ## [1] 479

``` r
baseline_raw_df |>
  filter(!is.na(age_at_onset)) |>
  nrow()
```

    ## [1] 97

``` r
baseline_new_df |>
  filter(!is.na(age_at_onset)) |>
  nrow()
```

    ## [1] 93

``` r
baseline_new_df |>
  summarize(avg_age = mean(current_age))
```

    ##   avg_age
    ## 1 65.0286

``` r
baseline_new_df |> 
  filter(sex == "Female") |> 
  summarize(women_carrier = mean(apoe4 == "Carrier"))
```

    ##   women_carrier
    ## 1           0.3

The important steps in importing baseline data is that I had to exclude
those who had MCI at baseline; I had to set up a condition to drop rows
that had MCI at baseline. Also, I had to change sex and apoe4 variables
from a numeric to character variable, so I used the case_match function.

There are 483 participants that were recruited, and 479 remain after
excluding those who had MCI at baseline. A total of 97 participants (4
at baseline, 93 at end of study) have developed MCI. For those not
excluded, the average baseline age is 65.03 years. The proportion of
women that are APOE4 carriers in the study is 0.3 (30%).
